version: '3'

services:
  pinscreen:
    build:
      context: .
      dockerfile: Dockerfile
    image: pinscreen:latest
    volumes:
      - /Users/justin/Desktop/pinscreen:/public
    ports:
      - 3000:3000